### ISSUE TITLE
Mouse Camera Speed drastically drops if VSync is switched off

### ISSUE THREAD

**Issue by nano13** [rbarongr/GodotFirstPersonController#2]
If you go to
settings -> Display -> Window
and disable V-Sync, the framerate will of course increase but the mouse speed will drop drastically. I am surprised by this behavior, as apparently you have factored in "delta" into the mouse movement, which is in my understanding exactly to avoid something like this.

However I find this behavior problematic. People should not need to adjust the mouse speed according to their framerates.

Do you have an idea where this behavior comes from and how to fix it?

Additional observation: Running Godot 4(.1) with disabled V-Sync has a good chance to crash just after a short while. Observed this on Windows and Linux. Maybe there is a bug in Godot according to disabled V-Sync?

**Comment by rbarongr** [comment]
Hi, I did a quick test and I can not replicate on macOS 13.1, Godot 4.0.3. The sensitivity is pretty much the same. It could be happening because of event.relative in the _input() function? **I will look more into it next week**.

And yes, we need to test it on Godot 4.1, it could be a crash due to a bug in Godot. There is an issue on the Godot Engine repository that seems to be related with the use of triplanar textures: godotengine/godot#71841. This could still be a problem, but is unrelated to this issue with the camera sensitivity.

**Comment by nano13** [comment]
Actually the setting of disabling VSync does not work allways reliably for me. Sometimes when I disable it, it is actually still on, and I have to enable and disable it again for getting it actually deactivated. You should use an FPS-Counter to be able to see if VSync is truly deactivated.

**Comment by rbarongr** [comment]
That seems like a bug in Godot, I suggest you report the issue in the Godot Engine repository.

**Comment by nano13** [comment]
True. The question is: Is the variation in the mouse speed i have observed on linux and windows with godot 4 and 4.1 related to this (or any) bug in the engine itself, or is there anything we could do in the First-Person Camera Controller to fix that?

**Comment by rbarongr** [comment]
The fact that VSync doesn't work every time for you and has a chance of crashing in runtime shouldn't have to do anything with this specific project. Have you tried on a new empty project? 🤔

The mouse speed not being consistent is something that _probably_ could be fix in this specific project. As I said, I will look into it in a few days. 🙂

**Comment by rbarongr** [comment]
Ok I have look at the problem and I think I have a solution. This is what is happening:

When I added gamepad support to the project I didn't take in consideration that camera rotation with the mouse is an absolute number but camera rotation with the gamepad (with the joypad) should be scaled with the delta time. By scaling the mouse rotation with delta time it was creating this inconsistency with the sensitivity.

What I have done is to handle the rotation separately and only taking care of the delta time when the gamepad is being used, leaving the mouse sensitivity as an absolute value in the `_unhandled_input()` method.

Please check the new branch with the new changes and test it. You can add the following code to the `_unhandled_input()` method to quickly change the VSync.

```gdscript
if Input.is_key_pressed(KEY_U):
	DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_DISABLED)
if Input.is_key_pressed(KEY_L):
	DisplayServer.window_set_vsync_mode(DisplayServer.VSYNC_ENABLED)
```

Press `U` to Unlock the framerate, and `L` to Lock it.

**Comment by nano13** [comment]
Thanks, that looks very good so far. I have added your changes to my own project getting now consistent mouse sensitivity independently of the framerate:

https://github.com/nano13/GodotFirstPersonController/blob/main/Player/CameraFPC.gd

The gamepad-sesitivity seems to be good, too.

In the next days I will test your vanilla branch, too.
