### ISSUE TITLE
using trackpad instead of mouse causes seemingly random movement

### ISSUE THREAD

**Issue by nano13** [rbarongr/GodotFirstPersonController#4]
Observing this one with Godot 4.1 on Linux:

Trying to use a laptop trackpad as the mouse will cause seemingly random movement. If I delete all gamepad assignments in the Input Map, the problem is solved. This means apparently Godot is taking trackpad inputs simultaniously as a mouse input (this would be correct) and additionally falsely as gamepad-inputs, too.

Can you reproduce this bug? If "yes": Is this a bug to be reported to upstream Godot or is there something we could do about it here?

**Comment by rbarongr** [comment]
The only trackpad that I can use right now is a trackpad from a M1 MacBook Air with macOS and the movement is normal. So I can't reproduce the bug.

What gamepad assignments are you deleting? The only Joypad Axis assignments I can see are from ui_left, ui_right, ui_up and ui_down, and those shouldn't be causing any trouble here. 🤔

**Comment by nano13** [comment]
I had to delete all of them, as otherwise trackpad movements resulted in jumping, strafing, moving forward, and all of that (additionally to the regular camera movement). The movement was however not boolean on/off as e.g. walking around with WASD, but depending on how much I have moved my finger on the trackpad resulted in different speeds, giving me the clue it has to mess around somehow with the gamepad code. However I have observed this bug already weeks ago, so it is not related to your latest commits. 

I do not have a Windows-Laptop (or Mac) available, so I will try to talk some friends of mine into testing it on Windows, too.

**Comment by rbarongr** [comment]
The inputs ui_left, ui_right, ui_up and ui_down are related to the left stick by default in Godot (Built-in actions), and in this project those are in charge of movement, so maybe for some reason Godot is treating the trackpad inputs as left stick inputs. But I don't understand why is jumping too 😅.

Maybe try to print the _event_ from `_unhandled_input(event: InputEvent)` to see what actions it is related to. This may give us some clues.

**Comment by nano13** [comment]
Here is some of the output of print(event):

```
InputEventJoypadMotion: axis=0, axis_value=-0.25
InputEventJoypadMotion: axis=1, axis_value=0.51
InputEventMouseMotion: button_mask=0, position=((640, 360)), relative=((0, -20)), velocity=((-39.94967, -269.6602)), pressure=0.00, tilt=((0, 0)), pen_inverted=(false)
InputEventJoypadMotion: axis=0, axis_value=-0.24
InputEventJoypadMotion: axis=1, axis_value=0.47
InputEventMouseMotion: button_mask=0, position=((640, 360)), relative=((3, -18)), velocity=((-39.94967, -269.6602)), pressure=0.00, tilt=((0, 0)), pen_inverted=(false)
InputEventJoypadMotion: axis=0, axis_value=-0.23
InputEventJoypadMotion: axis=1, axis_value=0.41
InputEventMouseMotion: button_mask=0, position=((640, 360)), relative=((3, -11)), velocity=((-39.94967, -269.6602)), pressure=0.00, tilt=((0, 0)), pen_inverted=(false)
InputEventJoypadMotion: axis=0, axis_value=-0.22
InputEventJoypadMotion: axis=1, axis_value=0.36
InputEventMouseMotion: button_mask=0, position=((640, 360)), relative=((5, -12)), velocity=((59.92869, -898.9304)), pressure=0.00, tilt=((0, 0)), pen_inverted=(false)
InputEventJoypadMotion: axis=0, axis_value=-0.22
InputEventJoypadMotion: axis=1, axis_value=0.34
InputEventMouseMotion: button_mask=0, position=((640, 360)), relative=((2, -5)), velocity=((59.92869, -898.9304)), pressure=0.00, tilt=((0, 0)), pen_inverted=(false)
InputEventJoypadMotion: axis=0, axis_value=-0.21
InputEventJoypadMotion: axis=1, axis_value=0.31
InputEventMouseMotion: button_mask=0, position=((640, 360)), relative=((2, -6)), velocity=((59.92869, -898.9304)), pressure=0.00, tilt=((0, 0)), pen_inverted=(false)
InputEventJoypadMotion: axis=0, axis_value=-0.21
InputEventJoypadMotion: axis=1, axis_value=0.29
InputEventMouseMotion: button_mask=0, position=((640, 360)), relative=((0, -1)), velocity=((59.92869, -898.9304)), pressure=0.00, tilt=((0, 0)), pen_inverted=(false)
InputEventJoypadMotion: axis=1, axis_value=0.29
InputEventMouseMotion: button_mask=0, position=((640, 360)), relative=((0, -1)), velocity=((59.92869, -898.9304)), pressure=0.00, tilt=((0, 0)), pen_inverted=(false)
InputEventJoypadButton: button_index=2, pressed=false, pressure=0.00
InputEventJoypadButton: button_index=0, pressed=false, pressure=0.00
InputEventJoypadMotion: axis=1, axis_value=0.28
InputEventKey: keycode=4194305 (Escape), mods=none, physical=false, pressed=true, echo=false
```

So it takes the trackpad motion as left stick and as mouse movement. Putting the finger onto the trackpad triggers a jump.

**Comment by rbarongr** [comment]
I think you should open a new empty project and test only this mouse behaviour, something like a MRP (Minimal Reproduction Project). If this bug keeps happening: report it to the Godot Engine repository. If this doesn't happens anymore... I really don't know why right now. But it seems like a Godot bug, this project is not _doing anything strange_ with the input, just reading and processing the values from it.
